### ISSUE TITLE
不能烤肉

### ISSUE THREAD

**Issue by wfcpc** [travellerse/ProofAcidFireCold#1]
不能烤肉了，排除肉
[HarmonyPatch(typeof(Card), "isFireproof", MethodType.Getter)]
    public static class ProofFirePatch
    {
        
        private static void Postfix(Card __instance, ref bool __result)
        {
            bool flag2 = __instance.category.IsChildOf("meat");
            if (flag2)
            {
                __result = false;
            }
            else
            {
                __result = true;
            }
           
        }
    }

**Comment by travellerse** [comment]
问一下烤肉是烤地上的还是能烤背包里的

**Comment by travellerse** [comment]
已经改了，上传创意工坊了
